
#config postgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/treino
spring.datasource.username=postgres
spring.datasource.password=7887
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
